version: "3"
services:
  springboot-app:
    container_name: spring-app
    restart: always
    image: rodrigomoreir4/springboot-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: admin123
      MYSQL_PORT: 3306

  mysqldb:
    container_name: mysqldb
    image: mysql:8.0.39
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: api-todo
      MYSQL_ROOT_PASSWORD: admin123

volumes:
  db_data: